app:
  name: lab-filter
  log-level: info

kafka:
  bootstrap-servers: localhost:9092
  security-protocol: ssl
  ssl:
    ca-location: /app/cert/kafka-ca.pem
    certificate-location: /app/cert/app-cert.pem
    key-location: /app/cert/app-key.pem
    key-password: private-key-password
  input-topic:
  output-topic:
  num-consumers: 3

fhir:
  profiles:
    service-request:
    diagnostic-report:
    observation: